project:
  type: website

website:
  title: "hyperopt handbook"
  navbar:
    background: primary
    search: true
    collapse-below: lg
    left:
      - href: index.html
        text: Home

      - text: Tutorials
        href: tutorials.qmd

      - text: How to Guides
        href: how_to_guides.qmd

      - text: Reference
        href: reference.qmd

      - about.qmd

sidebar:
  style: floating
format:
  html:
    theme: cosmo
    highlight-style: github
    css: styles.css
    toc: true
